apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gbv-bailer
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: gbv-bailer
            image: vlabresearch/bailer:0.0.9
            resources:
              requests:
                cpu: "250m"
                memory: "500Mi"
            envFrom:
            - secretRef:
                name: gbv-bot-envs
            env:
            - name: CHATBASE_DATABASE
              value: "chatroach"
            - name: CHATBASE_USER
              value: "chatroach"
            - name: CHATBASE_PASSWORD
              value: ""
            - name: CHATBASE_HOST
              value: "gbv-cockroachdb-public"
            - name: CHATBASE_PORT
              value: "26257"
            - name: BOTSERVER_URL
              value: "http://gbv-botserver"
            - name: BAILER_HOURS
              value: "24"
            - name: BAILER_DAYS
              value: "7"
            - name: BAILER_FORM_ENG
              value: "bailout_eng"
            - name: BAILER_FORM_HINDI
              value: "bailout_hindi"
            - name: BAILER_EXECUTE
              value: "true"
